[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["echo 'Installing dependencies...'"]

[phases.build]
cmds = ["echo 'Building static site...'"]

[start]
cmd = "python -m http.server $PORT"